### ISSUE TITLE
do you need to listen to all keydown events?

### ISSUE THREAD

**Issue by benadida** [mozilla/watchdog-visualhash#2]
https://github.com/mozilla/watchdog-visualhash/blob/master/Jetpack/data/js/util.js#L64

I'm guessing this is so you can catch all INPUTs, even ones added later, but just checking that this is necessary.

**Comment by psawaya** [comment]
Yeah, that might slow things down. Changed it to listen to DOM change events, which is working for me on Chrome and Firefox. I'm guessing those are a lot more rare.

**Comment by benadida** [comment]
Seems good, though now on the twitter login page nothing happens when my password is pre-filled until I type one more letter.

**Comment by psawaya** [comment]
Hmm, originally I wasn't going to have it show the hash on focus, but now that I think about it, it could be useful to see if your password manager filled in the password you thought it would. Let me know if you like the way it works now, and I'll resubmit to AMO.

Unfortunately, Chrome overrides the background of auto-filled password inputs to a yellowish color, so I don't think I can change the color until the user starts typing.

**Comment by benadida** [comment]
I don't think this requires a resubmit right now, let's get your add-on approved first, then we can rev it!
